---
name: ywsos2021_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  camera: ^0.8.1+5
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  gradient_widgets: ^0.6.0

  google_fonts: ^2.1.0
  flutter_secure_storage: ^4.2.1
  image_picker: ^0.8.2
  path: ^1.8.0
  path_provider: ^2.0.2
  provider: ^5.0.0
  timeago: ^3.1.0

dev_dependencies:
  analyzer: ^1.7.1
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
